/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.android.settings;

import android.content.Context;
import android.preference.SwitchPreference;
import android.util.AttributeSet;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Switch;

import com.mediatek.xlog.Xlog;

//caoqiaofeng add MTSFEFL-14 20150330

public class MySwitchPreference extends SwitchPreference {

    private static final String TAG = "MySwitchPreference";
	
    public MySwitchPreference(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }
    
    public MySwitchPreference(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    public MySwitchPreference(Context context) {
         super(context);
    }

    @Override
    protected void onClick() {
        Xlog.d(TAG, "onClick()");
    }
    
    @Override
    protected View onCreateView(ViewGroup parent) {
        View view = super.onCreateView(parent);
        Switch v = (Switch) view.findViewById(com.android.internal.R.id.switchWidget);
        if (v != null) {
            v.setClickable(true);
        }
        return view;
    }

}
