/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.android.launcher3;

import android.app.Activity;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.content.SharedPreferences;
import android.util.Log;
import android.content.Intent;
import android.content.ComponentName;
import android.widget.Toast;
import android.os.Bundle;

public class LoginLockedAppActivity extends Activity implements View.OnClickListener {
    public static final String IS_FIRST_LOGIN_AND_LOCKED = "isFirstLoginAndLocked";
    public static final String LOCK_PASSWD_SAVED = "lock_passwd_saved";
    private static final String TAG = "LoginLockedAppActivity";
    private ImageView delete;
    private ImageView digit0;
    private ImageView digit1;
    private ImageView digit2;
    private ImageView digit3;
    private ImageView digit4;
    private ImageView digit5;
    private ImageView digit6;
    private ImageView digit7;
    private ImageView digit8;
    private ImageView digit9;
    private boolean isEntryApp;
    private boolean isFirstLoginAndLocked;
    private String mClassName;
    private String mPackageName;
    private StringBuffer mPasswd;
    private TextView passwd;
    private TextView passwd_message;
    private TextView save;
    private String savePasswd;
    private SharedPreferences sp;
    private TextView tv_login_lock_title;
    
    public LoginLockedAppActivity() {
        mPasswd = new StringBuffer();
        isEntryApp = false;
        isFirstLoginAndLocked = true;
        sp = null;
        savePasswd = null;
    }
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.login_locked_app);
        mPackageName = getIntent().getStringExtra("PackageName");
        mClassName = getIntent().getStringExtra("ClassName");
        isEntryApp = getIntent().getBooleanExtra("isEntryApp", false);
        sp = getSharedPreferences("lock_app", 0x2);
        savePasswd = sp.getString("lock_passwd_saved", "");
        isFirstLoginAndLocked = sp.getBoolean("isFirstLoginAndLocked", true);
        initUI();
    }
    
    private void initUI() {
        digit0 = (ImageView)findViewById(R.id.digit0);
        digit1 = (ImageView)findViewById(R.id.digit1);
        digit2 = (ImageView)findViewById(R.id.digit2);
        digit3 = (ImageView)findViewById(R.id.digit3);
        digit4 = (ImageView)findViewById(R.id.digit4);
        digit5 = (ImageView)findViewById(R.id.digit5);
        digit6 = (ImageView)findViewById(R.id.digit6);
        digit7 = (ImageView)findViewById(R.id.digit7);
        digit8 = (ImageView)findViewById(R.id.digit8);
        digit9 = (ImageView)findViewById(R.id.digit9);
        delete = (ImageView)findViewById(R.id.delete);
        passwd = (TextView)findViewById(R.id.passwd);
        save = (TextView)findViewById(R.id.save);
        passwd_message = (TextView)findViewById(R.id.passwd_message);
        tv_login_lock_title = (TextView)findViewById(R.id.tv_login_lock_title);
        if(!isEntryApp) {
            tv_login_lock_title.setText(R.string.entry_lock_model);
        }
        if(!isFirstLoginAndLocked) {
            passwd_message.setText(R.string.entry_lock_model_introduction);
            tv_login_lock_title.setText(R.string.entry_lock_model);
        }
        digit0.setOnClickListener(this);
        digit1.setOnClickListener(this);
        digit2.setOnClickListener(this);
        digit3.setOnClickListener(this);
        digit4.setOnClickListener(this);
        digit5.setOnClickListener(this);
        digit6.setOnClickListener(this);
        digit7.setOnClickListener(this);
        digit8.setOnClickListener(this);
        digit9.setOnClickListener(this);
        delete.setOnClickListener(this);
        save.setOnClickListener(this);
    }
    
    public void onClick(View v) {
		switch(v.getId()){
			case R.id.digit0:
    			mPasswd.append("0");
    			break;
			case R.id.digit1:
    			mPasswd.append("1");
    			break;
			case R.id.digit2:
    			mPasswd.append("2");
    			break;
			case R.id.digit3:
    			mPasswd.append("3");
    			break;
			case R.id.digit4:
    			mPasswd.append("4");
    			break;
			case R.id.digit5:
    			mPasswd.append("5");
    			break;
			case R.id.digit6:
    			mPasswd.append("6");
    			break;
			case R.id.digit7:
    			mPasswd.append("7");
    			break;
			case R.id.digit8:
    			mPasswd.append("8");
    			break;
			case R.id.digit9:
    			mPasswd.append("9");
    			break;
			case R.id.delete:
				if(mPasswd.length() > 0)
					mPasswd.deleteCharAt(-1 + mPasswd.length());
    			break;
			case R.id.save:
				if(isFirstLoginAndLocked && null != mPasswd && !mPasswd.toString().trim().equals(""))
		        {
		            android.content.SharedPreferences.Editor editor = sp.edit();
		            editor.putString("lock_passwd_saved", mPasswd.toString());
		            editor.putBoolean("isFirstLoginAndLocked", false);
		            editor.commit();
		            isFirstLoginAndLocked = false;
		            startActivity(new Intent(this, ChooseLockAppActivity.class));
		            onDestroy();
		        }
				break;
		}
		
		//good passwd
        if(savePasswd != null && !savePasswd.toString().trim().equals("") && savePasswd.equals(mPasswd.toString()))
        {
            if(!isEntryApp)
                startActivity(new Intent(this, ChooseLockAppActivity.class));
            else
                startOriginActity();
            onDestroy();
        } 
        //error passwd
        else if(mPasswd != null && mPasswd.length() >= savePasswd.length() && isEntryApp){
            passwd_message.setVisibility(View.VISIBLE);
            passwd_message.setTextColor(0xffff0000);
        }else if(mPasswd != null && mPasswd.length() < savePasswd.length()){
            passwd_message.setVisibility(View.INVISIBLE);
        }
        
        //display * 
        StringBuilder stringbuffer = new StringBuilder(); 
        for(int i = 0; i < mPasswd.length(); i++){
        	stringbuffer.append("*");
        }
        passwd.setText(stringbuffer.toString());
        
        //dispaly or hide delete button
        if(mPasswd != null && mPasswd.length() >= 1)
            delete.setVisibility(View.VISIBLE);
        else
            delete.setVisibility(View.INVISIBLE);
    	
        //display or hide save button
    	if(isFirstLoginAndLocked && mPasswd != null && mPasswd.length() > 0){
            save.setVisibility(View.VISIBLE);            
        } else{
            save.setVisibility(View.INVISIBLE);            
        }        
    }
    
    private void startOriginActity() {
        Log.d("LoginLockedAppActivity", "mPackageName=" + mPackageName + " mClassName=" + mClassName);
        if((mPackageName != null) && (mClassName != null) && (!mPackageName.equals("")) && (!mClassName.equals(""))) {
            startActivity(new Intent().setComponent(new ComponentName(mPackageName, mClassName)));
            return;
        }
        Toast.makeText(this, R.string.unlocked_app_error, 0x0).show();
    }
    
    protected void onDestroy() {
        super.onDestroy();
        finish();
    }
}
