/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "mtkfb.h"
#include <cutils/log.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
//#include "utils/Log.h"

#ifndef _Included_com_android_settings_Goodix
#define _Included_com_android_settings_Goodix

#define OPEN_GESTRUE         0x50
#define CLOSE_GESTRUE       0x51
#define OPEN_GLOVE             0x53
#define CLOSE_GLOVE           0x54
//caoqiaofeng add MTSFEFL-14 20150323
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_settings_Goodix
 * Method:    enableStylus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_settings_Goodix_enableStylus
  (JNIEnv *env, jobject obj){	
	//int fd = open("dev/ft_rw_iic_drv", O_RDWR, 0);
	int fd = open("dev/ft_rw_iic_drv", O_RDWR);
	if (fd < 0) {
		//LOGE("OPEN Failed");
		return -100;
	} else {
		int ret = -1;
		if (ioctl(fd, OPEN_GLOVE, &ret) == -1) {
			//LOGE("ioctl Failed");
			close(fd);
			return -3;
		}
		close(fd);
		
		printf("enableStylus OK");
		return 1;
	}	
  }

/*
 * Class:     com_android_settings_Goodix
 * Method:    disableStylus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_settings_Goodix_disableStylus
  (JNIEnv *env, jobject obj){
	//int fd = open("dev/ft_rw_iic_drv", O_RDWR, 0);
	int fd = open("dev/ft_rw_iic_drv", O_RDWR);
	if (fd < 0) {
		//LOGE("OPEN Failed");
		return -10;
	} else {
		int ret = -1;
		if (ioctl(fd, CLOSE_GLOVE, &ret) == -1) {
			//LOGE("ioctl Failed");
			close(fd);
			return -3;
		}
		close(fd);
		printf("disableStylus OK");
		return 1;
	}
  }

/*
 * Class:     com_android_settings_Goodix
 * Method:    enableGesture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_settings_Goodix_enableGesture
  (JNIEnv *env, jobject obj){
	int fd = open("dev/ft_rw_iic_drv", O_RDWR, 0);
	if (fd < 0) {
		//LOGE("OPEN Failed");
		return -11;
	} else {
		int ret = -1;
		if (ioctl(fd, OPEN_GESTRUE, &ret) == -1) {
			//LOGE("ioctl Failed");
			close(fd);
			return -2;
		}
		
		close(fd);
		printf("enableGesture OK");
		return 1;
	}
  }

/*
 * Class:     com_android_settings_Goodix
 * Method:    disableGesture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_settings_Goodix_disableGesture
  (JNIEnv *env, jobject obj){
	int fd = open("dev/ft_rw_iic_drv", O_RDWR, 0);
	if (fd < 0) {
		//LOGE("OPEN Failed");
		return -12;
	} else {
	
		int ret = -1;
		if (ioctl(fd, CLOSE_GESTRUE, &ret) == -1) {
			//LOGE("ioctl Failed");
			close(fd);
			return -21;
		}
		
		close(fd);
		
		printf("disableGesture OK");
		return 1;
	}
  }

#ifdef __cplusplus
}
#endif
#endif
